"""
FluidX3D GPU CFD MCP tools — native GPU lattice-Boltzmann solver integration.

FluidX3D (ProjectPhysX/FluidX3D) runs on ALL GPUs via OpenCL — NVIDIA, AMD,
Intel Arc, Apple Silicon. 55 bytes/cell memory efficiency (6x better than
traditional LBM). 5k+ stars, v3.7 (May 2026), active maintenance.

These tools generate C++ setup files, compile via g++/MSVC, run the GPU
simulation, and parse structured output (forces, residuals, MLUPS throughput).

Requires: FluidX3D cloned locally. Default path auto-detected from common
locations; configurable via FLUIDX3D_PATH env var.

Registered via register_fluidx3d_tools(mcp, **deps) — called from server.py.
"""

import asyncio
import json
import logging
import os
import re
import shutil
import subprocess
from typing import Annotated

from pydantic import Field

logger = logging.getLogger("freecad-mcp.fluidx3d")

_README_ONLY = {"readonly": True}

# ── FluidX3D path detection ──────────────────────────────────────────────────

_FLUIDX3D_DEFAULT_PATHS = [
    r"D:\Dev\repos\FluidX3D",
    os.path.expanduser("~/FluidX3D"),
    os.path.expanduser("~/fluidx3d"),
    "/opt/FluidX3D",
]


def _find_fluidx3d() -> str | None:
    """Find FluidX3D installation from env var or common paths."""
    env_path = os.environ.get("FLUIDX3D_PATH")
    if env_path and os.path.isdir(env_path):
        return env_path
    for p in _FLUIDX3D_DEFAULT_PATHS:
        if os.path.isdir(p) and os.path.isdir(os.path.join(p, "src")):
            return p
    return None


def _find_compiler() -> str | None:
    """Find a C++ compiler (g++ preferred, then cl.exe)."""
    exes = ["g++", "g++-14", "g++-13", "g++-12", "clang++"]
    for exe in exes:
        try:
            r = subprocess.run([exe, "--version"], capture_output=True, text=True, timeout=5)  # noqa: S603
            if r.returncode == 0:
                return exe
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
    # Try MSVC
    try:
        r = subprocess.run(["cl"], capture_output=True, text=True, timeout=5, shell=True)  # noqa: S602, S607
        if "Microsoft" in r.stdout or "Microsoft" in r.stderr:
            return "cl"
    except Exception:
        logger.debug("MSVC compiler not available")
    return None


# ── Setup template ────────────────────────────────────────────────────────────

_TEMPLATE = """// FluidX3D setup — auto-generated by freecad-mcp cfd_fluidx3d_setup
// Case: {case_name} | Domain: {domain_type} | GPU CFD via OpenCL

void main_setup() {{
    const float lbm_len = {lbm_length}f;
    const float lbm_vel = {lbm_velocity}f;
    const float si_len = {si_length}f;
    const float si_vel = {si_velocity}f;

    units.set_m_kg_s(lbm_len, lbm_vel, 1.0f, si_len, si_vel, {si_density}f);

    const uint Nx = {Nx}u, Ny = {Ny}u, Nz = {Nz}u;
    const float nu = {nu}f;
    LBM lbm(Nx, Ny, Nz, nu, {fx}f, {fy}f, {fz}f);

    const uint N = lbm.get_N();
    const auto mid = lbm.center();

    parallel_for(N, [&](ulong n) {{
        uint x = 0u, y = 0u, z = 0u;
        lbm.coordinates(n, x, y, z);
        lbm.u.x[n] = lbm.u.y[n] = lbm.u.z[n] = 0.0f;
        lbm.rho[n] = 1.0f;
        lbm.flags[n] = 0u;
{boundary_code}
    }});
{stl_imports}

    const uint lbm_T = {time_steps}u;
    const uint write_intv = {write_interval}u;

    print_info("FluidX3D-MCP case:{case_name} res:" + to_string(Nx) + "x" + to_string(Ny) + "x" + to_string(Nz) + " cells:" + to_string(N) + " nu:" + to_string(nu));

    lbm.run(0u);
    const auto t0 = std::chrono::high_resolution_clock::now();

    while(lbm.get_t() < lbm_T) {{
        if(lbm.get_t() % write_intv == 0u && lbm.get_t() > 0u) {{
            const float3 f = lbm.object_force(TYPE_S);
            print_info("STEP " + to_string(lbm.get_t()) + " F " + to_string(units.si_F(f.x)) + " " + to_string(units.si_F(f.y)) + " " + to_string(units.si_F(f.z)));
            if(lbm.get_t() % (write_intv * 50u) == 0u) {{
                lbm.u.write_device_to_vtk();
                lbm.rho.write_device_to_vtk();
            }}
        }}
        lbm.run(1u);
    }}

    const auto t1 = std::chrono::high_resolution_clock::now();
    const float dt = std::chrono::duration<float>(t1 - t0).count();
    const float3 f = lbm.object_force(TYPE_S);

    print_info("DONE steps:" + to_string(lbm_T) + " time:" + to_string(dt) + "s mlups:" + to_string((float)N*(float)lbm_T/dt/1e6f));
    print_info("FORCES " + to_string(units.si_F(f.x)) + " " + to_string(units.si_F(f.y)) + " " + to_string(units.si_F(f.z)));

    lbm.u.write_device_to_vtk();
    lbm.rho.write_device_to_vtk();
}}
"""

# BC templates for common domain types
_BC_CHANNEL = """        if(x == 0u) {{ lbm.flags[n] = TYPE_E; lbm.u.x[n] = {u_inlet_x}f; lbm.u.y[n] = {u_inlet_y}f; lbm.u.z[n] = {u_inlet_z}f; }}
        else if(x == Nx - 1u) {{ lbm.flags[n] = TYPE_E; lbm.rho[n] = 1.0f; }}
        else if(y == 0u || y == Ny - 1u || z == 0u || z == Nz - 1u) {{ lbm.flags[n] = TYPE_S|TYPE_X; }}"""

_BC_PIPE = """        if(x == 0u) {{ lbm.flags[n] = TYPE_E; lbm.u.x[n] = {u_inlet_x}f; }}
        else if(x == Nx - 1u) {{ lbm.flags[n] = TYPE_E; lbm.rho[n] = 1.0f; }}
        else {{
            const float ry = (float)(int)y - (int)(Ny/2u);
            const float rz = (float)(int)z - (int)(Nz/2u);
            const float r2 = ry*ry + rz*rz;
            const float R2 = (float)(Ny/2u) * (float)(Ny/2u) * 0.95f;
            if(r2 > R2) {{ lbm.flags[n] = TYPE_S|TYPE_X; }}
        }}"""

_BC_BOX = """        if(x == 0u || x == Nx - 1u || y == 0u || y == Ny - 1u || z == 0u || z == Nz - 1u) {{ lbm.flags[n] = TYPE_S|TYPE_X; }}"""

BC_TEMPLATES = {
    "channel": _BC_CHANNEL,
    "pipe": _BC_PIPE,
    "box": _BC_BOX,
    "nozzle": _BC_PIPE,  # Same as pipe for now — STL import for complex
    "custom": "",
}


def _generate_boundary_code(
    domain_type: str,
    u_inlet_x: float,
    u_inlet_y: float,
    u_inlet_z: float,
    has_stl: bool = False,
) -> str:
    """Generate the boundary condition C++ code block."""
    if has_stl:
        return "        // Boundaries set via STL voxelization"
    template = BC_TEMPLATES.get(domain_type, _BC_BOX)
    return template.format(u_inlet_x=u_inlet_x, u_inlet_y=u_inlet_y, u_inlet_z=u_inlet_z)


def _generate_stl_imports(stl_files: list[str]) -> str:
    """Generate STL import C++ code."""
    if not stl_files:
        return "    // No STL geometry — using pure primitive boundaries"
    lines = []
    for i, stl_path in enumerate(stl_files):
        fname = os.path.basename(stl_path)
        lines.append(f'    Mesh* mesh_{i} = read_stl(get_exe_path() + "../stl/{fname}");')
        lines.append(f"    mesh_{i}->translate(mid - 0.5f * (mesh_{i}->pmin + mesh_{i}->pmax));")
        lines.append(f"    lbm.voxelize_mesh_on_device(mesh_{i}, TYPE_S|TYPE_X);")
    return "\n".join(lines)


def _generate_setup_cpp(
    case_name: str,
    domain_type: str,
    Nx: int, Ny: int, Nz: int,
    nu: float,
    lbm_length: float, lbm_velocity: float,
    si_length: float, si_velocity: float, si_density: float,
    fx: float, fy: float, fz: float,
    u_inlet_x: float, u_inlet_y: float, u_inlet_z: float,
    time_steps: int, write_interval: int,
    stl_files: list[str] | None = None,
) -> str:
    """Generate complete FluidX3D setup.cpp content."""
    stl_files = stl_files or []
    has_stl = len(stl_files) > 0

    return _TEMPLATE.format(
        case_name=case_name,
        domain_type=domain_type,
        Nx=Nx, Ny=Ny, Nz=Nz,
        nu=nu,
        lbm_length=lbm_length, lbm_velocity=lbm_velocity,
        si_length=si_length, si_velocity=si_velocity, si_density=si_density,
        fx=fx, fy=fy, fz=fz,
        boundary_code=_generate_boundary_code(domain_type, u_inlet_x, u_inlet_y, u_inlet_z, has_stl),
        stl_imports=_generate_stl_imports(stl_files),
        time_steps=time_steps,
        write_interval=write_interval,
    )


# ── Registration ──────────────────────────────────────────────────────────────


def register_fluidx3d_tools(
    mcp,
    state: dict,
    bridge_send,
    run_freecad,
    work_dir: str,
    output_dir: str,
    upload_dir: str,
    build_result,
):
    """Register all 6 FluidX3D MCP tools on the FastMCP instance.

    Returns a dict mapping tool_name -> callable for REST dispatch.
    """

    F3D_CASE_DIR = os.path.join(work_dir, "fluidx3d_cases")
    os.makedirs(F3D_CASE_DIR, exist_ok=True)

    # ── cfd_fluidx3d_status ──────────────────────────────────────────────

    @mcp.tool(annotations=_README_ONLY)
    async def cfd_fluidx3d_status() -> dict:
        """Check FluidX3D installation and compiler availability.

        Reports the FluidX3D source path, compiler found, and whether
        the pipeline is ready for GPU CFD. Call this first.

        ## Return Format
        {"success": bool, "fluidx3d_path": str, "compiler": str, "ready": bool}

        ## Examples
        await cfd_fluidx3d_status()
        """
        f3d_path = _find_fluidx3d()
        compiler = _find_compiler()
        ready = f3d_path is not None and compiler is not None

        if not f3d_path:
            return {
                "success": True,
                "fluidx3d_path": None,
                "compiler": compiler,
                "ready": False,
                "error": "FluidX3D not found. Clone: git clone https://github.com/ProjectPhysX/FluidX3D.git. Set env var FLUIDX3D_PATH if non-standard location.",
            }

        return {
            "success": True,
            "fluidx3d_path": f3d_path,
            "compiler": compiler or "not found",
            "ready": ready,
        }

    # ── cfd_fluidx3d_setup ──────────────────────────────────────────────

    @mcp.tool()
    async def cfd_fluidx3d_setup(
        case_name: Annotated[str, Field(description="Case directory name.")] = "f3d_channel",
        domain_type: Annotated[str, Field(description="Domain shape: channel, pipe, box, nozzle, stl.")] = "channel",
        resolution_x: Annotated[int, Field(description="Grid cells in X direction.", ge=16)] = 512,
        resolution_y: Annotated[int, Field(description="Grid cells in Y direction.", ge=16)] = 128,
        resolution_z: Annotated[int, Field(description="Grid cells in Z direction.", ge=16)] = 128,
        length_m: Annotated[float, Field(description="Physical length in metres.", ge=0.001)] = 1.0,
        velocity_ms: Annotated[float, Field(description="Inlet velocity in m/s.", ge=0.0001)] = 0.01,
        viscosity_m2s: Annotated[float, Field(description="Kinematic viscosity in m²/s.", ge=1e-10)] = 1e-6,
        density_kgm3: Annotated[float, Field(description="Fluid density in kg/m³.", ge=1e-6)] = 1000.0,
        time_steps: Annotated[int, Field(description="Total simulation time steps.", ge=100)] = 50000,
        write_interval: Annotated[int, Field(description="Write results every N steps.", ge=10)] = 1000,
        stl_file: Annotated[str, Field(description="STL filename in uploads for 'stl' domain type.")] = "",
    ) -> dict:
        """Generate a FluidX3D C++ setup file for GPU CFD simulation.

        Creates a complete setup.cpp with the specified domain, boundary
        conditions, and simulation parameters. The generated file replaces
        src/setup.cpp in a FluidX3D clone. Compile with cfd_fluidx3d_compile.

        Domain types:
        - channel: rectangular duct, velocity inlet/outlet, no-slip walls
        - pipe: cylindrical tube with circular cross-section
        - box: all-sides closed (driven cavity)
        - nozzle: convergent-divergent (STL import)
        - stl: custom geometry from STL file in uploads

        ## Return Format
        {"success": bool, "case_name": str, "data": {"setup_file": str, "resolution": str, "cells": int, "Re": float}}

        ## Examples
        await cfd_fluidx3d_setup(case_name="pipe_gpu", domain_type="pipe", resolution_x=512, resolution_y=128, resolution_z=128, length_m=2.0, velocity_ms=0.05)
        await cfd_fluidx3d_setup(case_name="airfoil_gpu", domain_type="stl", stl_file="naca0012.stl", resolution_x=768, time_steps=100000)
        """
        case_dir = os.path.join(F3D_CASE_DIR, case_name)
        os.makedirs(case_dir, exist_ok=True)

        # Handle STL file
        stl_files = []
        if domain_type == "stl" and stl_file:
            src = os.path.join(upload_dir, stl_file)
            if not os.path.isfile(src):
                src = os.path.join(output_dir, stl_file)
            if os.path.isfile(src):
                dst = os.path.join(case_dir, stl_file)
                shutil.copy(src, dst)
                stl_files = [dst]
            else:
                return {"success": False, "error": f"STL file '{stl_file}' not found in uploads or outputs."}

        # LBM unit conversion (keep u ≤ 0.1 for stability)
        lbm_velocity = min(velocity_ms * 0.05, 0.08)
        lbm_length = 1.0
        si_length = length_m
        si_velocity = velocity_ms

        # Viscosity in LBM units
        nu_si = viscosity_m2s
        lbm_nu = max(nu_si * lbm_velocity / (si_velocity * lbm_length) if si_velocity > 0 else 1.0 / 6.0, 0.001, min(0.2, 1.0 / 6.0))

        # Volume force (pressure gradient) for periodic boundaries
        fx = lbm_velocity * 1e-7
        fy = 0.0
        fz = 0.0

        ux = lbm_velocity
        uy = 0.0
        uz = 0.0

        # Generate C++ setup
        cpp_content = _generate_setup_cpp(
            case_name=case_name,
            domain_type=domain_type,
            Nx=resolution_x, Ny=resolution_y, Nz=resolution_z,
            nu=round(lbm_nu, 6),
            lbm_length=lbm_length, lbm_velocity=lbm_velocity,
            si_length=si_length, si_velocity=si_velocity, si_density=density_kgm3,
            fx=fx, fy=fy, fz=fz,
            u_inlet_x=ux, u_inlet_y=uy, u_inlet_z=uz,
            time_steps=time_steps, write_interval=write_interval,
            stl_files=stl_files if domain_type == "stl" else None,
        )

        setup_path = os.path.join(case_dir, "setup.cpp")
        with open(setup_path, "w") as f:
            f.write(cpp_content)

        # Also generate defines.hpp with required extensions
        extensions = "FORCE_FIELD EQUILIBRIUM_BOUNDARIES"
        if domain_type == "stl":
            extensions += " MOVING_BOUNDARIES"
        defines_content = f"""// FluidX3D extensions — auto-generated for case: {case_name}
#define FORCE_FIELD
#define EQUILIBRIUM_BOUNDARIES
"""
        defines_path = os.path.join(case_dir, "defines.hpp")
        with open(defines_path, "w") as f:
            f.write(defines_content)

        # Save config for later tools
        cfg = {
            "case_name": case_name,
            "domain_type": domain_type,
            "resolution": [resolution_x, resolution_y, resolution_z],
            "cells": resolution_x * resolution_y * resolution_z,
            "lbm_nu": round(lbm_nu, 6),
            "si_velocity": si_velocity,
            "si_viscosity": nu_si,
            "si_length": si_length,
            "time_steps": time_steps,
            "write_interval": write_interval,
        }
        Re = si_velocity * si_length / nu_si if nu_si > 0 else 0
        with open(os.path.join(case_dir, ".f3d_config.json"), "w") as f:
            json.dump(cfg, f)

        return {
            "success": True,
            "case_name": case_name,
            "data": {
                "setup_file": setup_path,
                "resolution": f"{resolution_x}x{resolution_y}x{resolution_z}",
                "cells": resolution_x * resolution_y * resolution_z,
                "Re_estimate": round(Re, 1),
                "lbm_nu": round(lbm_nu, 6),
                "lbm_velocity": round(lbm_velocity, 4),
            },
        }

    # ── cfd_fluidx3d_compile ────────────────────────────────────────────

    @mcp.tool()
    async def cfd_fluidx3d_compile(
        case_name: Annotated[str, Field(description="Case directory name.")],
        opencl_lib: Annotated[str, Field(description="OpenCL library path hint (auto-detected if empty).")] = "",
    ) -> dict:
        """Compile a FluidX3D case into an executable binary.

        Copies the generated setup.cpp and defines.hpp into the FluidX3D
        source tree, then compiles with g++ (Linux/Mac/WSL) or MSVC (Windows).
        Requires FluidX3D cloned locally and a C++ compiler.

        ## Return Format
        {"success": bool, "case_name": str, "data": {"binary": str, "compiler": str, "compile_time_s": float}}

        ## Examples
        await cfd_fluidx3d_compile(case_name="pipe_gpu")
        """
        f3d_path = _find_fluidx3d()
        if not f3d_path:
            return {"success": False, "error": "FluidX3D not found. Clone: git clone https://github.com/ProjectPhysX/FluidX3D.git"}

        compiler = _find_compiler()
        if not compiler:
            return {"success": False, "error": "No C++ compiler found. Install g++ (MinGW/WSL/Linux) or Visual Studio with MSVC."}

        case_dir = os.path.join(F3D_CASE_DIR, case_name)
        if not os.path.isdir(case_dir):
            return {"success": False, "error": f"Case '{case_name}' not found. Run cfd_fluidx3d_setup first."}

        setup_src = os.path.join(case_dir, "setup.cpp")
        defines_src = os.path.join(case_dir, "defines.hpp")
        if not os.path.isfile(setup_src):
            return {"success": False, "error": f"setup.cpp not found in case '{case_name}'. Run cfd_fluidx3d_setup first."}

        # Copy setup into FluidX3D source tree
        f3d_src = os.path.join(f3d_path, "src")
        if not os.path.isdir(f3d_src):
            return {"success": False, "error": f"FluidX3D src/ not found at {f3d_src}. Is FluidX3D cloned correctly?"}

        shutil.copy(setup_src, os.path.join(f3d_src, "setup.cpp"))
        shutil.copy(defines_src, os.path.join(f3d_src, "defines.hpp"))

        # Build binary path
        bin_dir = os.path.join(case_dir, "bin")
        os.makedirs(bin_dir, exist_ok=True)
        binary_name = f"fluidx3d_{case_name}" + (".exe" if os.name == "nt" else "")
        binary_path = os.path.join(bin_dir, binary_name)

        # Find all source files
        cpp_files = [os.path.join(f3d_src, f) for f in os.listdir(f3d_src) if f.endswith((".cpp", ".c"))]
        if not cpp_files:
            return {"success": False, "error": f"No C++ source files found in {f3d_src}"}

        import time
        t0 = time.time()

        if compiler == "cl":
            # MSVC compilation
            src_list = " ".join(f'"{f}"' for f in cpp_files)
            cmd = f'cl /EHsc /O2 /std:c++17 /Fe:"{binary_path}" {src_list} OpenCL.lib'
            try:
                proc = await asyncio.create_subprocess_shell(
                    cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                _stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=120)
            except TimeoutError:
                return {"success": False, "error": "MSVC compilation timed out"}
        elif "g++" in compiler or "clang" in compiler:
            # g++/clang++ compilation
            src_list = [os.path.join(f3d_src, f) for f in os.listdir(f3d_src) if f.endswith((".cpp", ".c"))]
            cmd = [compiler, "-std=c++17", "-O3", "-o", binary_path, *src_list, "-lOpenCL"]
            try:
                proc = await asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                _stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=120)
            except TimeoutError:
                return {"success": False, "error": "g++ compilation timed out"}
        else:
            return {"success": False, "error": f"Unsupported compiler: {compiler}"}

        dt = time.time() - t0
        stderr_text = stderr.decode("utf-8", errors="replace") if stderr else ""

        if proc.returncode != 0:
            return {
                "success": False,
                "error": f"Compilation failed (exit {proc.returncode})",
                "data": {"compiler": compiler, "stderr": stderr_text[-5000:]},
            }

        return {
            "success": True,
            "case_name": case_name,
            "data": {
                "binary": binary_path,
                "compiler": compiler,
                "compile_time_s": round(dt, 2),
                "warnings": stderr_text[:2000] if stderr_text else "",
            },
        }

    # ── cfd_fluidx3d_run ────────────────────────────────────────────────

    @mcp.tool()
    async def cfd_fluidx3d_run(
        case_name: Annotated[str, Field(description="Case directory name.")],
        gpu_device: Annotated[int, Field(description="OpenCL GPU device index (0 = auto-detect fastest).", ge=0)] = 0,
        timeout_s: Annotated[int, Field(description="Maximum runtime in seconds.", ge=10)] = 3600,
    ) -> dict:
        """Run a compiled FluidX3D simulation on the GPU.

        Executes the binary compiled by cfd_fluidx3d_compile. The simulation
        runs entirely on GPU via OpenCL. Captures stdout for force/residual
        parsing by cfd_fluidx3d_results.

        VTK output files are written to the FluidX3D binary's export directory
        (bin/export/). These can be loaded in ParaView for post-processing.

        ## Return Format
        {"success": bool, "case_name": str, "data": {"exit_code": int, "output": str, "runtime_s": float, "vtk_files": list}}

        ## Examples
        await cfd_fluidx3d_run(case_name="pipe_gpu")
        await cfd_fluidx3d_run(case_name="airfoil_gpu", gpu_device=0, timeout_s=7200)
        """
        case_dir = os.path.join(F3D_CASE_DIR, case_name)
        if not os.path.isdir(case_dir):
            return {"success": False, "error": f"Case '{case_name}' not found."}

        binary_name = f"fluidx3d_{case_name}" + (".exe" if os.name == "nt" else "")
        binary_path = os.path.join(case_dir, "bin", binary_name)

        if not os.path.isfile(binary_path):
            return {
                "success": False,
                "error": f"Binary not found at {binary_path}. Run cfd_fluidx3d_compile first.",
            }

        import time
        t0 = time.time()

        try:
            proc = await asyncio.create_subprocess_exec(
                binary_path, str(gpu_device),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout_s)
        except TimeoutError:
            return {
                "success": False,
                "error": f"Simulation timed out after {timeout_s}s",
                "data": {"exit_code": -1},
            }

        dt = time.time() - t0
        out_text = stdout.decode("utf-8", errors="replace")
        err_text = stderr.decode("utf-8", errors="replace")

        # Save output to case directory for later analysis
        log_path = os.path.join(case_dir, "run.log")
        with open(log_path, "w") as f:
            f.write(out_text)
            if err_text:
                f.write("\n=== STDERR ===\n")
                f.write(err_text)

        # Find VTK files
        vtk_files = []
        for root, dirs, files in os.walk(case_dir):
            for fn in files:
                if fn.endswith(".vtk"):
                    vtk_files.append(os.path.join(root, fn))
        # Also check FluidX3D export directory
        f3d_path = _find_fluidx3d()
        if f3d_path:
            export_dir = os.path.join(f3d_path, "bin", "export")
            if os.path.isdir(export_dir):
                for fn in os.listdir(export_dir):
                    if fn.endswith(".vtk"):
                        vtk_files.append(os.path.join(export_dir, fn))

        return {
            "success": proc.returncode == 0,
            "case_name": case_name,
            "data": {
                "exit_code": proc.returncode or 0,
                "output": out_text[-10000:],
                "stderr": err_text[-2000:] if err_text else "",
                "runtime_s": round(dt, 2),
                "vtk_files": vtk_files[:50],
                "log_file": log_path,
            },
        }

    # ── cfd_fluidx3d_results ────────────────────────────────────────────

    @mcp.tool(annotations=_README_ONLY)
    async def cfd_fluidx3d_results(
        case_name: Annotated[str, Field(description="Case directory name.")],
    ) -> dict:
        """Parse FluidX3D simulation results from the run log.

        Extracts forces, throughput (MLUPS), time step history, and
        whether the simulation completed successfully.

        ## Return Format
        {"success": bool, "case_name": str, "data": {"forces": list, "final_forces": {"Fx": float, "Fy": float, "Fz": float}, "mlups": float, "time_steps": int, "completed": bool}}

        ## Examples
        await cfd_fluidx3d_results(case_name="pipe_gpu")
        """
        case_dir = os.path.join(F3D_CASE_DIR, case_name)
        if not os.path.isdir(case_dir):
            return {"success": False, "error": f"Case '{case_name}' not found."}

        log_path = os.path.join(case_dir, "run.log")
        if not os.path.isfile(log_path):
            return {"success": False, "error": "No run log found. Run cfd_fluidx3d_run first."}

        with open(log_path) as f:
            content = f.read()

        # Parse STEP lines: "STEP <N> F <Fx> <Fy> <Fz>"
        forces = []
        for match in re.finditer(r"STEP (\d+) F ([\d.e+\-]+) ([\d.e+\-]+) ([\d.e+\-]+)", content):
            forces.append({
                "step": int(match.group(1)),
                "Fx": float(match.group(2)),
                "Fy": float(match.group(3)),
                "Fz": float(match.group(4)),
            })

        # Parse DONE line
        done_match = re.search(r"DONE steps:(\d+) time:([\d.]+)s mlups:([\d.]+)", content)
        completed = done_match is not None
        total_steps = int(done_match.group(1)) if done_match else 0
        runtime = float(done_match.group(2)) if done_match else 0
        mlups = float(done_match.group(3)) if done_match else 0

        # Parse FINAL_FORCES or FORCES line
        final_forces = {"Fx": 0.0, "Fy": 0.0, "Fz": 0.0}
        force_match = re.search(r"(?:FINAL_)?FORCES ([\d.e+\-]+) ([\d.e+\-]+) ([\d.e+\-]+)", content)
        if force_match:
            final_forces = {
                "Fx": float(force_match.group(1)),
                "Fy": float(force_match.group(2)),
                "Fz": float(force_match.group(3)),
            }

        # Load config for context
        cfg = {}
        cfg_path = os.path.join(case_dir, ".f3d_config.json")
        if os.path.isfile(cfg_path):
            with open(cfg_path) as f:
                cfg = json.load(f)

        return {
            "success": True,
            "case_name": case_name,
            "data": {
                "forces": forces[-100:],
                "force_count": len(forces),
                "final_forces": final_forces,
                "mlups": round(mlups, 2),
                "mlups_unit": "Million Lattice Updates Per Second",
                "time_steps_completed": total_steps,
                "runtime_s": round(runtime, 2),
                "completed": completed,
                "config": cfg,
            },
        }

    # ── cfd_fluidx3d_explain ─────────────────────────────────────────────

    @mcp.tool(annotations=_README_ONLY)
    async def cfd_fluidx3d_explain(
        case_name: Annotated[str, Field(description="Case directory name.")],
    ) -> dict:
        """Explain what a FluidX3D simulation would compute and how to interpret results.

        Reads the stored config and provides a human-readable summary of the
        flow physics, expected Reynolds number, and what the forces mean.

        ## Return Format
        {"success": bool, "case_name": str, "data": {"summary": str, "Re": float, "regime": str, "solver_notes": str}}

        ## Examples
        await cfd_fluidx3d_explain(case_name="pipe_gpu")
        """
        cfg_path = os.path.join(F3D_CASE_DIR, case_name, ".f3d_config.json")
        if not os.path.isfile(cfg_path):
            return {"success": False, "error": f"Case '{case_name}' not found or no config saved."}

        with open(cfg_path) as f:
            cfg = json.load(f)

        v = cfg.get("si_velocity", 0)
        L = cfg.get("si_length", 0)
        nu = cfg.get("si_viscosity", 0)
        Re = v * L / nu if nu > 0 else 0
        res = cfg.get("resolution", [0, 0, 0])
        cells = res[0] * res[1] * res[2]
        domain = cfg.get("domain_type", "unknown")

        if Re < 1:
            regime = "creeping/stokes flow — viscous forces dominate, linear flow"
        elif Re < 2300:
            regime = "laminar — smooth streamlines, predictable, no turbulent mixing"
        elif Re < 10000:
            regime = "transitional — intermittent turbulence, sensitive to perturbations"
        else:
            regime = "turbulent — chaotic eddies, enhanced mixing, subgrid model active"

        if domain == "pipe":
            if Re < 2300:
                regime += ". Darcy friction factor f ≈ 64/Re."
            else:
                regime += ". Blasius: f ≈ 0.316/Re^0.25 (smooth pipe)."

        summary = (
            f"FluidX3D GPU simulation of {domain} flow. "
            f"{cells:,} cells on a {res[0]}x{res[1]}x{res[2]} grid. "
            f"Inlet velocity {v} m/s, domain length {L} m, "
            f"kinematic viscosity {nu:.2e} m²/s. "
            f"Reynolds number Re = {Re:,.1f} — {regime} "
            f"FluidX3D uses the lattice-Boltzmann method (LBM) with "
            f"D3Q19 velocity set and single-relaxation-time (SRT/BGK) collision. "
            f"The Smagorinsky-Lilly subgrid model handles turbulence at high Re."
        )

        solver_notes = (
            "LBM is an explicit solver — time steps are small (~10^-5 s in SI) "
            "but throughput is high (100s of MLUPS on GPU). "
            "Forces are summed over all solid boundary cells marked TYPE_S|TYPE_X. "
            "VTK output files contain volumetric velocity and density fields "
            "for post-processing in ParaView or further ML analysis."
        )

        return {
            "success": True,
            "case_name": case_name,
            "data": {
                "summary": summary,
                "Re": round(Re, 1),
                "regime": regime,
                "solver_notes": solver_notes,
            },
        }

    logger.info(
        "FluidX3D tools registered: cfd_fluidx3d_status, cfd_fluidx3d_setup, cfd_fluidx3d_compile, "
        "cfd_fluidx3d_run, cfd_fluidx3d_results, cfd_fluidx3d_explain"
    )

    return {
        "cfd_fluidx3d_status": cfd_fluidx3d_status,
        "cfd_fluidx3d_setup": cfd_fluidx3d_setup,
        "cfd_fluidx3d_compile": cfd_fluidx3d_compile,
        "cfd_fluidx3d_run": cfd_fluidx3d_run,
        "cfd_fluidx3d_results": cfd_fluidx3d_results,
        "cfd_fluidx3d_explain": cfd_fluidx3d_explain,
    }
