// FluidX3D Runner — replaces src/setup.cpp in a FluidX3D clone.
// Reads config.json at runtime for simulation parameters.
// Compile once, run many cases without recompilation.
//
// Usage: fluidx3d_runner <config.json> [gpu_device]
//
// Config JSON schema (auto-generated by cfd_fluidx3d_setup):
// {
//   "case_name": "...",           // Case identifier (used in output)
//   "domain": { ... },            // Domain dimensions
//   "fluid": { "nu": 0.01, ... }, // Fluid properties (LBM units)
//   "inlet": {"velocity": [0.1, 0, 0]},  // Inlet BC (LBM units)
//   "outlet": {"type": "equilibrium"},
//   "stl_files": [],              // STL meshes to load
//   "control": {"time_steps": 50000, "write_interval": 1000},
//   "boundaries": { ... },        // Per-boundary flags
//   "si_conversion": { ... }      // SI ↔ LBM unit conversion factors
// }

#include <chrono>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include <cstring>

// ── Required FluidX3D defines ─────────────────────────────────────────────
#define FORCE_FIELD
#define EQUILIBRIUM_BOUNDARIES

// ── FluidX3D includes (from the clone's src/ directory) ──────────────────
#include "src/defines.hpp"
#include "src/lbm.hpp"
#include "src/units.hpp"
#include "src/shapes.hpp"
#include "src/utilities.hpp"

// ── Simple JSON reader (minimal, single-header style) ─────────────────────

static std::string json_get_string(const std::string& json, const std::string& key, size_t& pos) {
    auto k = "\"" + key + "\"";
    auto p = json.find(k, pos);
    if (p == std::string::npos) return "";
    auto c = json.find(':', p + k.size());
    if (c == std::string::npos) return "";
    auto s = json.find_first_of("\"", c);
    if (s == std::string::npos) return "";
    auto e = json.find_first_of("\"", s + 1);
    if (e == std::string::npos) return "";
    pos = e + 1;
    return json.substr(s + 1, e - s - 1);
}

static float json_get_float(const std::string& json, const std::string& key, size_t& pos) {
    auto k = "\"" + key + "\"";
    auto p = json.find(k, pos);
    if (p == std::string::npos) return 0.0f;
    auto c = json.find(':', p + k.size());
    if (c == std::string::npos) return 0.0f;
    auto s = json.find_first_of("-0123456789", c);
    if (s == std::string::npos) return 0.0f;
    auto e = json.find_first_not_of(".0123456789eE+-", s + 1);
    if (e == std::string::npos) e = json.size();
    pos = e + 1;
    return std::stof(json.substr(s, e - s));
}

static int json_get_int(const std::string& json, const std::string& key, size_t& pos) {
    return (int)json_get_float(json, key, pos);
}

static void json_get_array(const std::string& json, const std::string& key, std::vector<float>& out, size_t& pos) {
    out.clear();
    auto k = "\"" + key + "\"";
    auto p = json.find(k, pos);
    if (p == std::string::npos) return;
    auto c = json.find(':', p + k.size());
    if (c == std::string::npos) return;
    auto s = json.find('[', c);
    if (s == std::string::npos) return;
    auto epos = s + 1;
    while (true) {
        auto v = json.find_first_of("-0123456789.", epos);
        if (v == std::string::npos || json[v - 1] == ']') break;
        auto vend = json.find_first_not_of(".0123456789eE+-", v + 1);
        out.push_back(std::stof(json.substr(v, vend - v)));
        epos = vend;
        if (json[vend] == ']') break;
    }
    pos = epos + 1;
}


// ── Main setup (read by FluidX3D's build system) ─────────────────────────

void main_setup() {
    // Read config file from argv (set via environment or command file)
    std::string config_path = "config.json";
    auto env_path = getenv("F3D_CONFIG");
    if (env_path && strlen(env_path) > 0) config_path = env_path;

    std::ifstream f(config_path);
    if (!f.is_open()) {
        print_error("Runner: cannot open config: " + config_path);
        print_info("RESULT {\"error\": \"Cannot open config file: " + config_path + "\", \"success\": false}");
        return;
    }
    std::string cfg((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
    f.close();

    // Parse config
    size_t pos = 0;
    auto case_name = json_get_string(cfg, "case_name", pos);
    float nu = json_get_float(cfg, "nu", pos);
    int Nx = json_get_int(cfg, "Nx", pos);
    int Ny = json_get_int(cfg, "Ny", pos);
    int Nz = json_get_int(cfg, "Nz", pos);
    int time_steps = json_get_int(cfg, "time_steps", pos);
    int write_interval = json_get_int(cfg, "write_interval", pos);
    float si_length = json_get_float(cfg, "si_length", pos);
    float si_velocity = json_get_float(cfg, "si_velocity", pos);
    float si_density = json_get_float(cfg, "si_density", pos);
    float lbm_length = json_get_float(cfg, "lbm_length", pos);
    float lbm_velocity = json_get_float(cfg, "lbm_velocity", pos);

    std::vector<float> inlet_vel;
    json_get_array(cfg, "inlet_velocity", inlet_vel, pos);
    float ux = inlet_vel.size() > 0 ? inlet_vel[0] : lbm_velocity;
    float uy = inlet_vel.size() > 1 ? inlet_vel[1] : 0.0f;
    float uz = inlet_vel.size() > 2 ? inlet_vel[2] : 0.0f;

    float fx = json_get_float(cfg, "fx", pos);
    float fy = json_get_float(cfg, "fy", pos);
    float fz = json_get_float(cfg, "fz", pos);
    std::string domain_type = json_get_string(cfg, "domain_type", pos);

    // Unit conversion
    units.set_m_kg_s(lbm_length, lbm_velocity, 1.0f, si_length, si_velocity, si_density);

    if (Nx < 4 || Ny < 4 || Nz < 4) {
        print_info("RESULT {\"error\": \"Resolution too small\", \"success\": false}");
        return;
    }

    LBM lbm((uint)Nx, (uint)Ny, (uint)Nz, nu, fx, fy, fz);
    const auto N = lbm.get_N();
    const auto mid = lbm.center();

    print_info("RUNNER case:" + case_name + " res:" + to_string(Nx) + "x" + to_string(Ny) + "x" + to_string(Nz)
        + " cells:" + to_string(N) + " nu:" + to_string(nu));

    // Set boundary conditions
    parallel_for(N, [&](ulong n) {
        uint x = 0u, y = 0u, z = 0u;
        lbm.coordinates(n, x, y, z);
        lbm.u.x[n] = lbm.u.y[n] = lbm.u.z[n] = 0.0f;
        lbm.rho[n] = 1.0f;
        lbm.flags[n] = 0u;

        if (domain_type == "pipe") {
            if (x == 0u) { lbm.flags[n] = TYPE_E; lbm.u.x[n] = ux; }
            else if (x == Nx - 1u) { lbm.flags[n] = TYPE_E; lbm.rho[n] = 1.0f; }
            else {
                auto cy = (float)(int)y - (float)(int)Ny * 0.5f;
                auto cz = (float)(int)z - (float)(int)Nz * 0.5f;
                auto R2 = (float)(Ny / 2u) * (float)(Ny / 2u) * 0.95f;
                if (cy * cy + cz * cz > R2) lbm.flags[n] = TYPE_S;
            }
        } else if (domain_type == "channel") {
            if (x == 0u) { lbm.flags[n] = TYPE_E; lbm.u.x[n] = ux; lbm.u.y[n] = uy; lbm.u.z[n] = uz; }
            else if (x == Nx - 1u) { lbm.flags[n] = TYPE_E; lbm.rho[n] = 1.0f; }
            else if (y == 0u || y == Ny - 1u || z == 0u || z == Nz - 1u) { lbm.flags[n] = TYPE_S; }
        } else {
            // box / default: all sides solid
            if (x == 0u || x == Nx - 1u || y == 0u || y == Ny - 1u || z == 0u || z == Nz - 1u)
                lbm.flags[n] = TYPE_S;
        }
    });

    // STL import
    // STL files path: read stl_files array from config
    // FluidX3D reads STL from ../stl/ relative to executable
    pos = 0;
    auto stl_section_start = cfg.find("\"stl_files\"", pos);
    if (stl_section_start != std::string::npos) {
        auto arr_start = cfg.find('[', stl_section_start);
        if (arr_start != std::string::npos) {
            auto stl_pos = arr_start + 1;
            while (true) {
                auto qs = cfg.find_first_of("\"", stl_pos);
                if (qs == std::string::npos || qs >= cfg.size() - 1) break;
                auto qe = cfg.find_first_of("\"", qs + 1);
                if (qe == std::string::npos) break;
                auto stl_name = cfg.substr(qs + 1, qe - qs - 1);
                stl_pos = qe + 1;
                if (stl_name.empty()) break;
                print_info("Runner loading STL: " + stl_name);
                auto mesh = read_stl(get_exe_path() + "../stl/" + stl_name);
                mesh->translate(mid - 0.5f * (mesh->pmin + mesh->pmax));
                lbm.voxelize_mesh_on_device(mesh, TYPE_S);
                delete mesh;
                if (cfg[qe + 1] == ']') break;
            }
        }
    }

    // Run
    lbm.run(0u);
    const auto t0 = std::chrono::high_resolution_clock::now();

    while (lbm.get_t() < (uint)time_steps) {
        if (lbm.get_t() % (uint)write_interval == 0u && lbm.get_t() > 0u) {
            const float3 f = lbm.object_force(TYPE_S);
            print_info("STEP " + to_string(lbm.get_t()) + " F "
                + to_string(units.si_F(f.x)) + " "
                + to_string(units.si_F(f.y)) + " "
                + to_string(units.si_F(f.z)));
            if (lbm.get_t() % (uint)(write_interval * 50u) == 0u) {
                lbm.u.write_device_to_vtk();
                lbm.rho.write_device_to_vtk();
            }
        }
        lbm.run(1u);
    }

    const auto t1 = std::chrono::high_resolution_clock::now();
    const float dt = std::chrono::duration<float>(t1 - t0).count();
    const float3 f = lbm.object_force(TYPE_S);
    const float mlups = (float)N * (float)time_steps / dt / 1e6f;

    // Final VTK
    lbm.u.write_device_to_vtk();
    lbm.rho.write_device_to_vtk();

    // Structured JSON output for MCP parsing
    print_info("RESULT {\"success\":true,\"case\":\"" + case_name
        + "\",\"completed\":true,\"time_steps\":" + to_string(time_steps)
        + ",\"runtime_s\":" + to_string(dt)
        + ",\"mlups\":" + to_string(mlups)
        + ",\"final_forces\":{\"Fx\":" + to_string(units.si_F(f.x))
        + ",\"Fy\":" + to_string(units.si_F(f.y))
        + ",\"Fz\":" + to_string(units.si_F(f.z)) + "}}");
}
