<#
.SYNOPSIS
    Build the FluidX3D Runner - a standalone GPU CFD binary.
    Compiles runner.cpp against a FluidX3D clone to produce a single executable
    that reads config.json at runtime (no recompilation per case).

.DESCRIPTION
    The runner "bakes in" the FluidX3D LBM solver core at compile time, then
    accepts a JSON config at runtime for all simulation parameters (resolution,
    viscosity, inlet velocity, time steps, STL files, etc.).

    Two modes:
    1. Automatic: clones FluidX3D if not found, compiles the runner
    2. Manual: specify FLUIDX3D_PATH if already cloned

.PARAMETER FluidX3DPath
    Path to an existing FluidX3D clone. Auto-detected if not specified.

.PARAMETER OutputDir
    Where to place the compiled binary. Default: fluidx3d_runner/bin/

.PARAMETER Compiler
    Which compiler to use: "g++" (default, for Linux/Mac/MinGW) or "msvc" (Windows MSVC).

.EXAMPLE
    .\build-fluidx3d-runner.ps1
    .\build-fluidx3d-runner.ps1 -Compiler msvc
    .\build-fluidx3d-runner.ps1 -FluidX3DPath D:\Dev\repos\FluidX3D -Compiler g++
#>

param(
    [string]$FluidX3DPath = "",
    [string]$OutputDir = "",
    [string]$Compiler = ""
)

$ErrorActionPreference = "Stop"
$ScriptRoot = Split-Path -Parent $PSCommandPath
$RepoRoot = Resolve-Path (Join-Path $ScriptRoot "..")
$RunnerDir = Join-Path $RepoRoot "src\freecad_mcp\fluidx3d_runner"
$RunnerSrc = Join-Path $RunnerDir "runner.cpp"

# Auto-detect FluidX3D
if (-not $FluidX3DPath) {
    $candidates = @(
        $env:FLUIDX3D_PATH,
        "D:\Dev\repos\FluidX3D",
        "$env:USERPROFILE\FluidX3D",
        "$env:HOMEDRIVE$env:HOMEPATH\FluidX3D",
        "/opt/FluidX3D"
    )
    foreach ($c in $candidates) {
        if ($c -and (Test-Path "$c\src\lbm.hpp" -or (Test-Path "$c/src/lbm.hpp"))) {
            $FluidX3DPath = $c; break
        }
    }
}

if (-not $FluidX3DPath -or -not (Test-Path $FluidX3DPath)) {
    Write-Host "FluidX3D not found. Cloning..." -ForegroundColor Yellow
    $FluidX3DPath = Join-Path $RepoRoot "FluidX3D"
    & git clone "https://github.com/ProjectPhysX/FluidX3D.git" $FluidX3DPath
    if (-not $?) { throw "Failed to clone FluidX3D" }
    Write-Host "Cloned to $FluidX3DPath" -ForegroundColor Green
}

if (-not $OutputDir) { $OutputDir = Join-Path $RunnerDir "bin" }
New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

if (-not $Compiler) {
    # Auto-detect compiler
    $gpp = Get-Command "g++" -ErrorAction SilentlyContinue
    $cl = Get-Command "cl" -ErrorAction SilentlyContinue
    if ($gpp) { $Compiler = "g++" }
    elseif ($cl) { $Compiler = "msvc" }
    else {
        Write-Host "No C++ compiler found. Install g++ (via MinGW/Git Bash) or Visual Studio/MSVC." -ForegroundColor Red
        exit 1
    }
}

# Copy runner.cpp into FluidX3D src/ as setup.cpp
$F3DSrc = Join-Path $FluidX3DPath "src"
if (-not (Test-Path $F3DSrc)) { throw "FluidX3D src/ not found at $F3DSrc" }
Copy-Item $RunnerSrc (Join-Path $F3DSrc "setup.cpp") -Force

# Generate defines.hpp
$Defines = @"
// FluidX3D Runner defines - auto-generated by build-fluidx3d-runner.ps1
#define FORCE_FIELD
#define EQUILIBRIUM_BOUNDARIES
"@
Set-Content -Path (Join-Path $F3DSrc "defines.hpp") -Value $Defines -Force

$BinaryName = "fluidx3d-runner.exe"
$BinaryPath = Join-Path $OutputDir $BinaryName
$Triple = "x86_64-pc-windows-msvc"
$DevDir = Join-Path $RunnerDir "binaries"
New-Item -ItemType Directory -Force -Path $DevDir | Out-Null

Write-Host "=== FluidX3D Runner Build ===" -ForegroundColor Cyan
Write-Host "Source: $RunnerSrc" -ForegroundColor Gray
Write-Host "Output: $BinaryPath" -ForegroundColor Gray
Write-Host "Compiler: $Compiler" -ForegroundColor Gray
Write-Host "FluidX3D: $FluidX3DPath" -ForegroundColor Gray

$t0 = Get-Date

if ($Compiler -eq "g++") {
    $srcFiles = Get-ChildItem -Path $F3DSrc -Filter "*.cpp" | ForEach-Object { $_.FullName }
    $srcList = $srcFiles -join " "
    $cmd = "g++ -std=c++17 -O3 -o `"$BinaryPath`" $srcList -lOpenCL"
    Write-Host "  g++ compile..." -ForegroundColor Yellow
    Invoke-Expression $cmd
    if ($LASTEXITCODE -ne 0) { throw "g++ compilation failed with exit code $LASTEXITCODE" }
}
elseif ($Compiler -eq "msvc") {
    $srcFiles = Get-ChildItem -Path $F3DSrc -Filter "*.cpp" | ForEach-Object { "`"$($_.FullName)`"" }
    $srcList = $srcFiles -join " "
    $cmd = "cl /EHsc /O2 /std:c++17 /Fe:`"$BinaryPath`" $srcList OpenCL.lib"
    Write-Host "  MSVC compile..." -ForegroundColor Yellow
    Invoke-Expression "cmd /c `"$cmd`""
    if ($LASTEXITCODE -ne 0) { throw "MSVC compilation failed with exit code $LASTEXITCODE" }
}

$dt = (Get-Date) - $t0
$size = (Get-Item $BinaryPath).Length
Write-Host "=== Build complete ===" -ForegroundColor Green
Write-Host "Binary: $BinaryPath ($([math]::Round($size / 1MB, 2)) MB)"
Write-Host "Compile time: $($dt.TotalSeconds.ToString('F1'))s"

# Copy to dev fallback location
$devBinary = Join-Path $DevDir "fluidx3d-runner-$Triple.exe"
Copy-Item $BinaryPath $devBinary -Force
Write-Host "Dev copy: $devBinary" -ForegroundColor Gray
