/*
 * FluidX3D setup template — auto-generated by freecad-mcp cfd_fluidx3d_setup.
 *
 * This file replaces src/setup.cpp in a FluidX3D clone.
 * Compile with: g++ -std=c++17 -O3 -o fluidx3d_run src/*.cpp -lOpenCL
 * Or on Windows with MSVC: cl /EHsc /O2 /Fe:fluidx3d_run.exe src/*.cpp OpenCL.lib
 *
 * Generated for case: {case_name}
 * Domain type: {domain_type}
 * Resolution: {Nx}×{Ny}×{Nz}
 * Viscosity (LBM units): {nu}
 * Inlet velocity (LBM units): ({u_inlet_x}, {u_inlet_y}, {u_inlet_z})
 * Time steps: {time_steps}
 */

#include "src/defines.hpp"

// ── Uncomment required extensions ──────────────────────────────────────
#define FORCE_FIELD
#define EQUILIBRIUM_BOUNDARIES
{extensions}

void main_setup() {{
    // ── Unit conversion ────────────────────────────────────────────────
    // LBM units: rho=1, u≈0.001-0.1, nu tuned for stability
    const float lbm_length = {lbm_length}f;
    const float lbm_velocity = {lbm_velocity}f;
    const float si_length = {si_length}f;    // m
    const float si_velocity = {si_velocity}f; // m/s

    units.set_m_kg_s(lbm_length, lbm_velocity, 1.0f, si_length, si_velocity, {si_density}f);

    // ── Simulation box ─────────────────────────────────────────────────
    const uint Nx = {Nx}u;
    const uint Ny = {Ny}u;
    const uint Nz = {Nz}u;
    const float nu = {nu}f;
    const float fx = {fx}f;
    const float fy = {fy}f;
    const float fz = {fz}f;

    LBM lbm(Nx, Ny, Nz, nu, fx, fy, fz);
    const uint N = lbm.get_N();

    // ── Initial & boundary conditions ──────────────────────────────────
    parallel_for(N, [&](ulong n) {{
        uint x = 0u, y = 0u, z = 0u;
        lbm.coordinates(n, x, y, z);

        // Default: fluid at rest
        lbm.u.x[n] = 0.0f;
        lbm.u.y[n] = 0.0f;
        lbm.u.z[n] = 0.0f;
        lbm.rho[n] = 1.0f;
        lbm.flags[n] = 0u;

{boundary_code}
    }});

    // ── STL geometry import ────────────────────────────────────────────
{stl_imports}

    // ── Run simulation ─────────────────────────────────────────────────
    const uint lbm_T = {time_steps}u;
    const uint write_interval = {write_interval}u;
    const float fx_si = {fx_si}f;  // N/m³
    const float fy_si = {fy_si}f;
    const float fz_si = {fz_si}f;

    lbm.run(0u);  // Initialize (copy to GPU)

    // Print header for progress parsing
    print_info("FluidX3D MCP — case: {case_name}");
    print_info("Resolution: " + to_string(Nx) + "x" + to_string(Ny) + "x" + to_string(Nz)
        + " (" + to_string(N) + " cells)");
    print_info("nu (LBM): " + to_string(nu) + ", Re_estimate: " + to_string(si_length * si_velocity / units.si_nu(nu)));

    const auto t_start = std::chrono::high_resolution_clock::now();

    while(lbm.get_t() < lbm_T) {{
        // Compute forces on wall boundaries every write_interval steps
        if(lbm.get_t() % write_interval == 0u && lbm.get_t() > 0u) {{
            const float3 force = lbm.object_force(TYPE_S);
            const float si_Fx = units.si_F(force.x);
            const float si_Fy = units.si_F(force.y);
            const float si_Fz = units.si_F(force.z);

            // Print structured JSON-compatible output for MCP parsing
            print_info("STEP " + to_string(lbm.get_t()) + " FORCES "
                + to_string(si_Fx) + " " + to_string(si_Fy) + " " + to_string(si_Fz));

            // Export VTK every 10*write_interval
            if(lbm.get_t() % (write_interval * 10u) == 0u) {{
                lbm.u.write_device_to_vtk();
                lbm.rho.write_device_to_vtk();
            }}
        }}

        lbm.run(1u);
    }}

    const auto t_end = std::chrono::high_resolution_clock::now();
    const float elapsed = std::chrono::duration<float>(t_end - t_start).count();

    // Final force extraction
    const float3 force = lbm.object_force(TYPE_S);
    const float si_Fx = units.si_F(force.x);
    const float si_Fy = units.si_F(force.y);
    const float si_Fz = units.si_F(force.z);

    print_info("COMPLETE " + to_string(lbm_T) + " steps in " + to_string(elapsed) + "s");
    print_info("FINAL_FORCES " + to_string(si_Fx) + " " + to_string(si_Fy) + " " + to_string(si_Fz));
    print_info("MLUPS " + to_string((float)N * (float)lbm_T / elapsed / 1e6f));

    // Final VTK export
    lbm.u.write_device_to_vtk();
    lbm.rho.write_device_to_vtk();

    print_info("DONE");
}}
